/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_jewsaten_opencvsamples_OpenCVUtil */

#ifndef _Included_io_jewsaten_opencvsamples_OpenCVUtil
#define _Included_io_jewsaten_opencvsamples_OpenCVUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_jewsaten_opencvsamples_OpenCVUtil
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_io_jewsaten_opencvsamples_OpenCVUtil_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
